### ISSUE TITLE
hover popup disappears after "updatetime" milliseconds has passed in a terminal

### ISSUE THREAD

**Issue by vrischmann** [myitcv/govim#332] opened 2019-07-04 12:09 UTC
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun 28 2019 09:32:51)
Included patches: 1-1602
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl/dyn          +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           +python/dyn        +visual
+cmdline_info      +libcall           +python3/dyn       +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          +ruby/dyn          +wildmenu
+cursorbind        +lua/dyn           +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      -sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary
+extra_search      +mouse_sgr         -tag_old_static
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim81"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/gio-unix-2.0 -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm  -lselinux   -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc
</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.12.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vincent/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vincent/dev/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build999686884=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What version/commit of `govim` are you using?

a4bb8b0004f695e8dd80aae6c9f7389fdf6ad77f

### What is the output of `:messages` in Vim?

> Messages maintainer: Mike Williams <mrw@eandem.co.uk>

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

In the vim channel file, after hovering on a type:

```
 39.197738 SEND on 0(in): '[40,["function","function:GOVIM_internal_BalloonExpr",[]]]
'
 39.197764 on 0: Blocking read JSON for id 40
 39.197768 : looking for messages on channels
 39.197771 on 0: Waiting for up to 30000 msec
 39.198130 RECV on 0(out): '[0,[35,"expr","{\"bufnum\": v:beval_bufnr, \"line\": v:beval_lnum, \"col\": v:beval_col}"]]
'
 39.198151 : looking for messages on channels
 39.198163 on 0: Getting JSON message 0
 39.198168 on 0: Invoking channel callback <SNR>27_define
 39.198383 SEND on 0(in): '[41,["callback",35,["",{"bufnum":1,"col":10,"line":3}]]]
'
 39.198411 : looking for messages on channels
 39.198418 on 0: Waiting for up to 30000 msec
 39.198589 RECV on 0(out): '[40,["",""]]
'
 39.198602 on 0: Getting JSON message 40
 39.198611 on 0: Received JSON for id 40
 39.199352 RECV on 0(out): '[0,[36,"call","balloon_show",["var typ string"]]]
'
 39.199359 : looking for messages on channels
 39.199379 on 0: Getting JSON message 0
 39.199382 on 0: Invoking channel callback <SNR>27_define
 39.199594 SEND on 0(in): '[42,["callback",36,["",0]]]
'
 39.247749 : looking for messages on channels
```

### How did you install `govim`?

Vim 8 Package

### What did you do?

With this vimrc:

```
set nocompatible
set nobackup
set nowritebackup
set noswapfile

filetype plugin on

set mouse=a

set ttymouse=sgr

set updatetime=300
set balloondelay=250

syntax on
```

and this code:

```go
package main

func do(typ string) int {
	return len(typ)
}

func main() {
	do("foobar")
}
```

I opened the Go file _in a terminal_ (this is important), I hovered on `typ`.

### What did you expect to see?

The popup with hover information stays on screen indefinitely.

### What did you see instead?

The popup is shown but it doesn't stay on the screen despite me not moving the mouse.

The amount of time it stays on screen seems to also depend on what `updatetime` is: if I set `updatetime` to 10000 it looks like the popup stays for 10s on screen.

Note that this doesn't happen in gvim.

**Comment by myitcv** [comment] 2019-07-04 13:19
Thanks for the report. I think this is a duplicate of https://github.com/myitcv/govim/issues/148 so will close your issue. 

However, thank you for the observation that this is linked to `updatetime`. I have noted this in https://github.com/vim/vim/issues/4273#issuecomment-489465306

**Closed by myitcv** 2019-07-04 13:19 UTC

**Comment by vrischmann** [comment] 2019-07-04 13:27
Sorry, I missed that issue, I must have used the wrong search terms. I'll check the other issue.

**Comment by myitcv** [comment] 2019-07-04 13:42
No apology needed! The term "balloon" is not the first term you'd expect to search for. For that reason I just added https://github.com/myitcv/govim/issues/148#issuecomment-508487099 to make it more easily searchable.
